[package]
name = "socket"
version = "0.1.0"
authors = ["Dmitrii Goriunov <goriunovd@gmail.com>"]

[dependencies]
mio = "0.6"
slab = "0.4"

[lib]
name = "socket"
path = "src/lib.rs"

[[bin]]
name = "socket_bin"
path = "src/bin.rs"
